# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
hello_world_func <- function() {
    invisible(.Call(`_GSMVAEx_hello_world_func`))
}

#' @export
loglog <- function(tobs, event, X, XD, eps, kappa, beta) {
    .Call(`_GSMVAEx_loglog`, tobs, event, X, XD, eps, kappa, beta)
}

