# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
optim_VA_boost <- function(y, x, sigma_log, beta, lambda_log, mu, grp_size, order) {
    .Call(`_SimpleVAPois_optim_VA_boost`, y, x, sigma_log, beta, lambda_log, mu, grp_size, order)
}

