// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// optim_VA_boost
Rcpp::List optim_VA_boost(arma::vec const& y, arma::vec const& x, double const sigma_log, arma::vec const& beta, arma::vec const& lambda_log, arma::vec const& mu, unsigned const grp_size, unsigned const order);
RcppExport SEXP _SimpleVAPois_optim_VA_boost(SEXP ySEXP, SEXP xSEXP, SEXP sigma_logSEXP, SEXP betaSEXP, SEXP lambda_logSEXP, SEXP muSEXP, SEXP grp_sizeSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec const& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double const >::type sigma_log(sigma_logSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type lambda_log(lambda_logSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< unsigned const >::type grp_size(grp_sizeSEXP);
    Rcpp::traits::input_parameter< unsigned const >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_VA_boost(y, x, sigma_log, beta, lambda_log, mu, grp_size, order));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SimpleVAPois_optim_VA_boost", (DL_FUNC) &_SimpleVAPois_optim_VA_boost, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_SimpleVAPois(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
